kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name:  create-deployments
rules:
 - apiGroups: ["*"]
   resources: ["deployments","pods/*","services","secrets","networkpolicies.networking.k8s.io","pods"]
   verbs: ["get","list","watch","create","update","patch","apply"]
